### PR TITLE
install jq on heroku dyno

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**
the script for syncing the images that runs on heroku is currently
erroring out with:

    ./script/sync-images: line 140: jq: command not found

this change, as well as:

    heroku buildpacks:add https://github.com/heroku/heroku-buildpack-apt

should ensure that jq is installed.

### CODE REVIEW

**Comment by bogdanap** [comment]
I noticed that we should already be installing jq here: https://github.com/travis-ci/job-board/blob/master/script/sync-images#L139, so I'd be curious to first find out what went wrong there before replacing the behaviour.

**Comment by bogdanap** [comment]
Oh, on second thought, I guess the `command not found` message is the output from the initial check (`jq --version`), before we actually install jq. 
That being said, I think I like the buildpack idea better than the current approach.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
ah, totally missed that, very nice find!

i'm happy to also change the check to use `command -v`. awaiting @meatballhat input. :)

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Closing stale PR.

**Pull request closed without merging**
